services:
  - type: web
    name: feedback-intelite
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SUPERVISOR_SUPORTE_PASSWORD
        sync: false
      - key: SUPERVISOR_COMERCIAL_PASSWORD
        sync: false
      - key: SUPERVISOR_RH_PASSWORD
        sync: false
